### ISSUE TITLE
AIAct_Tick_Patch break game AI

### ISSUE THREAD

**Issue by Nathan8489** [Redgeioz/ElinAutoAct#2]
有時候一個 AIAct 根本不需要檢查 Child 是否成功，會使用 `onChildFail` 覆蓋子任務的回傳狀態。
`AIWork` 就是這樣一個例子。

所以遊戲中會出現以下合法狀態。
```
this.child.status == AIAct.Status.Fail
this.onChildFail == ()=>AIAct.Status.Running;
```

此時該 Chara 接下來所有回合都會被強制用於發呆。
https://github.com/Redgeioz/ElinAutoAct/blob/64e8b0ace54e9fe6d1a4cb232aba36965cd491b1/GeneralActions.cs#L814-L832

**Comment by Redgeioz** [comment]
这段代码是为了解决自动状态下的TaskHarvest无法被敌人打断而加的，child被敌人打断后进入fail状态，而主行动tick无法检测到child的fail状态直接进入success()

**Comment by Redgeioz** [comment]
所以应该限定为仅对TaskHarvest实现这个检查？

**Comment by Redgeioz** [comment]
我觉得可以改成这样
```jsx
  if (__instance.child != null && __instance.child.status == AIAct.Status.Fail)
  {
      if (__instance.onChildFail != null)
      {
          __result = __instance.onChildFail();
          __instance.child = null;
          return false;
      }
      __result = AIAct.Status.Fail;
      return false;
  }
```

**Comment by Redgeioz** [comment]
懂你意思了，感谢指出

**Comment by Nathan8489** [comment]
commit https://github.com/Redgeioz/ElinAutoAct/commit/99b89fe7741beab5b780d3d8eb33e6489c62b41e
修正了錯誤
目前也未發現該 patch 可能會導致的其他問題
因此 close issue
